CREATE SCHEMA IF NOT EXISTS BANCO;
USE BANCO;

CREATE TABLE IF NOT EXISTS MONTOTRANSACCION(
	Codigo int NOT NULL AUTO_INCREMENT,
	Estado BOOLEAN NOT NULL,
	Monto Double NOT NULL,
	PRIMARY KEY(Codigo)
);

CREATE TABLE IF NOT EXISTS MONTOTRANSACCIONVARIAS(
	Codigo int NOT NULL AUTO_INCREMENT,
	Estado BOOLEAN NOT NULL,
	Cantidad int NOT NULL,
	Monto Double NOT NULL,
	PRIMARY KEY(Codigo)
);

INSERT INTO MONTOTRANSACCION (Estado, Monto) VALUES(True, 200);
INSERT INTO MONTOTRANSACCIONVARIAS (Estado, Cantidad,Monto) VALUES(True,5,2000);

CREATE TABLE IF NOT EXISTS USUARIO(
	Codigo VARCHAR(700) NOT NULL,
	Password VARBINARY(8000) NOT NULL,
	Tipo VARCHAR(25) NOT NULL,
	PRIMARY KEY(Codigo)
);

CREATE TABLE IF NOT EXISTS CAJERO(
	DPI VARCHAR(15) NOT NULL,
	Nombre VARCHAR(500) NOT NULL,
	Turno VARCHAR(100) NOT NULL,
	Direccion VARCHAR(2000) NOT NULL,
	Sexo VARCHAR(100) NOT NULL,
	NoUsuario VARCHAR(700) NOT NULL,
	PRIMARY KEY(DPI),
	FOREIGN KEY(NoUsuario) REFERENCES USUARIO(Codigo)
);

CREATE TABLE IF NOT EXISTS GERENTE (
	DPI VARCHAR(15) NOT NULL,
	Nombre VARCHAR(500) NOT NULL,
	Turno VARCHAR(100) NOT NULL,
	Direccion VARCHAR(2000) NOT NULL,
	Sexo VARCHAR(100) NOT NULL,
	NoUsuario VARCHAR(700) NOT NULL,
	PRIMARY KEY (DPI),
	FOREIGN KEY (NoUsuario) REFERENCES USUARIO(Codigo)
);

CREATE TABLE IF NOT EXISTS CLIENTE (
	DPI VARCHAR(15) NOT NULL,
	Nombre VARCHAR(500) NOT NULL,
	FechaNacimiento DATE NOT NULL,
	Direccion VARCHAR(2000) NOT NULL,
	Sexo VARCHAR(100) NOT NULL,
	DireccionPDF TEXT NOT NULL,
	NoUsuario VARCHAR(700) NOT NULL,
	PRIMARY KEY (DPI),
	FOREIGN KEY (NoUsuario) REFERENCES USUARIO (Codigo)
);

CREATE TABLE IF NOT EXISTS HISTORIAL_ACTUALIZACIONES (
	NoActualizacion INT NOT NULL AUTO_INCREMENT,
	HoraActualizacion TIME NOT NULL,
	FechaActualizacion DATE NOT NULL,
	DescripcionCambio TEXT NOT NULL,
	IDGerente VARCHAR(15) NOT NULL,
	IDUsuario VARCHAR(700),
	PRIMARY KEY (NoActualizacion),
	FOREIGN KEY(IDGerente) REFERENCES GERENTE (DPI),
	FOREIGN KEY(IDUsuario) REFERENCES USUARIO (Codigo)
);

CREATE TABLE IF NOT EXISTS CUENTA (
	Codigo VARCHAR(200) NOT NULL,
	FechaCreacion DATE NOT NULL,
	Credito DOUBLE NOT NULL,
	IDCliente VARCHAR(15) NOT NULL,
	PRIMARY KEY (Codigo),
	FOREIGN KEY(IDCliente) REFERENCES CLIENTE(DPI)
);

CREATE TABLE IF NOT EXISTS CUENTAS_ASOCIADAS(
	NoAsociacion INT NOT NULL AUTO_INCREMENT,
	IDCuentaA VARCHAR(200) NOT NULL,
	IDCuentaB VARCHAR(200) NOT NULL,
	Estado VARCHAR(15) NOT NULL,
	PRIMARY KEY (NoAsociacion),
	FOREIGN KEY(IDCuentaA) REFERENCES CUENTA (Codigo),
	FOREIGN KEY(IDCuentaB) REFERENCES CUENTA (Codigo)
);

CREATE TABLE IF NOT EXISTS TRANSACCION (
	Codigo int NOT NULL AUTO_INCREMENT,
	FechaRealizacion DATE NOT NULL,
	HoraRealizacion TIME NOT NULL,
	Monto DOUBLE NOT NULL,
	Tipo VARCHAR(100) NOT NULL,
	IDCajero VARCHAR(700) NOT NULL,
	Cuenta VARCHAR(200) NOT NULL,
	PRIMARY KEY (Codigo),
	FOREIGN KEY (IDCajero) REFERENCES USUARIO(Codigo),
	FOREIGN KEY (Cuenta) REFERENCES CUENTA (Codigo)
);
